# basic options
title: dross
author: tomchatter
email: your-email@domain.com
description: research dross
twitter_username: ttt
github_username:  tomchatter

# Build settings
markdown: kramdown

theme: minima
